
name: Actualizar Excel Diario

on:
  schedule:
    - cron: '0 3 * * *'  # Ejecuta todos los días a las 3:00 AM UTC
  workflow_dispatch:

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: pip install pandas openpyxl

    - name: Ejecutar script de actualización
      run: python actualizar_excel.py

    - name: Commit y push de cambios
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add Calculo\\ ventana\\ de\\ cambio.xlsx
        git co
